TYPES = {
    "weapon": [
        "shortsword",
        "blade",
        "claymore",
        "dagger",
        "staff",
        "longbow",
        "recurve bow",
        "crossbow",
        "mace",
        "war hammer",
        "halberd",
        "halberd",
        "spear",
        "scimitar",
        "battle axe",
        "falchion",
        "club",
        "morning star",
        "glaive",
        "scythe",
    ],

    "armor": [
        "gorget",
        "cuirass",
        "plackart",
        "cowter",
        "spaulders",
        "vambraces",
        "gauntlets",
        "graves",
        "cuisse",
        "sabatons",
        "faulds",
        "pauldrons",
        "gousset",
    ],

    "magic": [
        "potion",
        "ring",
        "philter",
        "ring",
        "amulet",
        "scroll",
        "cloak",
        "circlet",
        "dust",
        "gem",
        "orb",
        "tome",
        "talisman",
        "stone",
        "shard",
        "crystal",
        "horn",
    ],

    "common": [
        "chains",
        "cuffs",
        "urn",
        "rubble",
        "crate",
        "rags",
        "parchment",
        "lamp",
        "candle",
        "torch",
        "bedroll",
        "journal",
        "book",
        "shelves",
        "rope",
        "straw",
        "wood",
        "teeth",
        "bones",
        "pottery",
        "dust",
        "chair",
        "stool",
        "blanket",
        "charcoal",
        "pail",
        "incense",
        "beaker",
        "alembic",
        "cauldron",
        "bowl",
        "decanter",
        "mortar",
        "pestle",
        "funnel",
        "flask",
        "skull",
        "ash",
        "cinders",
        "bandages",
        "cup",
        "flagon",
        "pot",
    ],
}


DESCRIPTORS = {
    "adjectives": [
        "ghastly",
        "addictive",
        "gilded",
        "beautiful",
        "valorous",
        "ancient",
        "magnificent",
        "strange",
        "fearful",
        "splendid",
        "horrible",
        "luminous",
        "furious",
        "shameful",
        "friendly",
        "piteous",
        "weeping",
        "splendiferous",
        "blunderous",
        "magnetic",
        "electric",
        "burning",
        "brutal",
        "savage",
        "graceful",
        "volcanic",
        "ornate",
        "bloody",
        "ashen",
        "gleaming",
        "glittering",
        "eldritch",
        "eery",
        "elegant",
        "exquisite",
        "munificent",
        "noxious",
        "nefarious",
        "repulsive",
        "repugnant",
        "bewildering",
        "dusky",
        "stormy",
        "somnolent",
        "envious",
        "grotesque",
    ],

    "verbs": [
        "of blooding",
        "of governing",
        "of torpor",
        "of somnolence",
        "of jubilance",
        "of repulsion",
        "of reckoning",
        "of mourning",
        "of grieving",
        "of judgement",
        "of battering",
        "of scorching",
        "of smite",
        "of waning",
        "of smiting",
        "of crushing",
        "of extraction",
        "of valor",
        "of fear",
        "of firestorms",
        "of icestorms",
        "of ice",
        "of thunder",
        "of lightning",
        "of hatred",
        "of terror",
        "of ruin",
        "of ruining",
        "of fury",
        "of disgust",
        "of friendship",
        "of calming",
        "of shame",
        "of pity",
        "of envy",
        "of suffering",
        "of weeping",
        "of disdain",
        "of contempt",
        "of mediocrity",
        "of misery",
        "of thorns",
        "of light",
        "of dark",
        "of darkness",
        "of dawn",
        "of dusk",
        "of twilight",
        "of brutality",
        "of savagery",
        "of quickening",
        "of grace",
        "of disintegration",
        "of disintegrating",
        "of embalming",
        "of destruction",
        "of exsanguination"
    ]
}


QUALITIES = {
    "common": [
        "rusty",
        "ruined",
        "broken",
        "dusty",
        "cobwebbed",
        "untouched",
        "worn",
        "rotted",
        "dirty",
        "old",
        "mended",
        "decayed",
        "burnt",
        "intact",
        "unblemished",
        "decrepit",
        "derelict",
        "tattered",
        "shabby",
        "wretched",
        "shattered",
    ],

    "uncommon": [
        "common",
        "rare",
        "rusty",
        "dusty",
        "cobwebbed",
        "ruined",
        "broken",
        "untouched",
        "worn",
        "pristine",
        "polished",
        "chipped",
        "flawless",
        "mended",
        "damaged",
        "old",
        "durable",
        "weakened",
        "fragile",
        "shiny",
        "fine",
        "adequate",
        "dirty",
        "barbed",
        "thorny",
    ]
}


MATERIALS = [
    "golden",
    "silver",
    "glass",
    "bone",
    "onyx",
    "obsidian",
    "amethyst",
    "iron",
    "steel",
    "leather",
    "wood",
    "emerald",
    "jade",
    "turquoise",
    "ivory",
    "fur",
    "bronze",
    "copper",
    "meteorite",
    "stone",
    "adamantine",
]