TYPES = {
    "weapon": [
        "shortsword",
        "blade",
        "claymore",
        "dagger",
        "staff",
        "longbow",
        "recurve bow",
        "crossbow",
        "mace",
        "war hammer",
        "halberd",
        "halberd",
        "spear",
        "scimitar",
        "battle axe",
        "falchion",
        "club",
        "morning star",
        "glaive",
        "scythe",
    ],

    "armor": [
        "gorget",
        "cuirass",
        "plackart",
        "cowter",
        "spaulders",
        "vambraces",
        "gauntlets",
        "greaves",
        "cuisse",
        "sabatons",
        "faulds",
        "pauldrons",
        "gousset",
    ],

    "magic": [
        "potion",
        "ring",
        "philter",
        "ring",
        "amulet",
        "scroll",
        "cloak",
        "circlet",
        "dust",
        "gem",
        "orb",
        "tome",
        "talisman",
        "magestone",
        "shard",
        "crystal",
        "horn",
    ],

    "common": [
        "chains",
        "cuffs",
        "urn",
        "rubble",
        "crate",
        "rags",
        "parchment",
        "lamp",
        "candle",
        "torch",
        "bedroll",
        "journal",
        "book",
        "shelves",
        "rope",
        "straw",
        "wood",
        "teeth",
        "bones",
        "pottery",
        "dust",
        "chair",
        "stool",
        "blanket",
        "charcoal",
        "pail",
        "incense",
        "beaker",
        "alembic",
        "cauldron",
        "bowl",
        "decanter",
        "mortar",
        "pestle",
        "funnel",
        "flask",
        "skull",
        "ash",
        "cinders",
        "bandages",
        "cup",
        "flagon",
        "pot",
    ],
}


DESCRIPTORS = {
    "adjectives": [
        "ghastly",
        "addictive",
        "gilded",
        "beautiful",
        "valorous",
        "ancient",
        "magnificent",
        "strange",
        "fearful",
        "splendid",
        "horrible",
        "luminous",
        "furious",
        "shameful",
        "friendly",
        "piteous",
        "weeping",
        "splendiferous",
        "loathsome",
        "blunderous",
        "magnetic",
        "electric",
        "burning",
        "brutal",
        "savage",
        "graceful",
        "volcanic",
        "uncanny",
        "spectral",
        "sinister",
        "ornate",
        "bloody",
        "ashen",
        "gleaming",
        "glittering",
        "eldritch",
        "eerie",
        "elegant",
        "exquisite",
        "munificent",
        "ineffable",
        "mirthful",
        "noxious",
        "nefarious",
        "repulsive",
        "freakish",
        "bewitched",
        "repugnant",
        "exotic",
        "burdensome",
        "vigilant",
        "bewildering",
        "chosen",
        "dazzling",
        "dusky",
        "putrid",
        "unpleasant",
        "bizarre",
        "frenzied",
        "stormy",
        "erosive",
        "vengeful",
        "somnolent",
        "opulent",
        "lustrous",
        "hideous",
        "insideous",
        "spiteful",
        "ugly",
        "ghoulish",
        "soulless",
        "corrupted",
        "envious",
        "grotesque",
        "weeping",
    ],

    "verbs": [
        "of blooding",
        "of humiliation",
        "of hubris",
        "of spite",
        "of death",
        "of life",
        "of regret",
        "of lust",
        "of carving",
        "of surprise",
        "of confusion",
        "of frenzy",
        "of breaking",
        "of loathing",
        "of sickness",
        "of poisons",
        "of tragedy",
        "of souls",
        "of rotting",
        "of governing",
        "of ecstasy",
        "of torpor",
        "of truth",
        "of lies",
        "of victory",
        "of ambition",
        "of vengeance",
        "of somnolence",
        "of joy",
        "of corruption",
        "of erosion",
        "of jubilance",
        "of merit",
        "of witching",
        "of burdens",
        "of honor",
        "of repulsion",
        "of reckoning",
        "of mourning",
        "of grieving",
        "of judgement",
        "of battering",
        "of the night",
        "of the stars",
        "of starlight",
        "of scorching",
        "of smite",
        "of waning",
        "of smiting",
        "of diffusion",
        "of mummification",
        "of crushing",
        "of extraction",
        "of valor",
        "of fear",
        "of firestorms",
        "of icestorms",
        "of ice",
        "of thunder",
        "of lightning",
        "of hatred",
        "of terror",
        "of ruin",
        "of ruining",
        "of fury",
        "of disgust",
        "of friendship",
        "of calming",
        "of shame",
        "of pity",
        "of envy",
        "of suffering",
        "of weeping",
        "of disdain",
        "of putrification",
        "of contempt",
        "of mediocrity",
        "of misery",
        "of thorns",
        "of light",
        "of dark",
        "of darkness",
        "of dawn",
        "of dusk",
        "of twilight",
        "of brutality",
        "of savagery",
        "of quickening",
        "of grace",
        "of disintegration",
        "of disintegrating",
        "of embalming",
        "of destruction",
        "of exsanguination",
    ]
}


QUALITIES = {
    "common": [
        "rusty",
        "ruined",
        "broken",
        "dusty",
        "cobwebbed",
        "untouched",
        "worn",
        "rotted",
        "dirty",
        "old",
        "mended",
        "decayed",
        "burnt",
        "intact",
        "unblemished",
        "decrepit",
        "derelict",
        "tattered",
        "shabby",
        "wretched",
        "shattered",
    ],

    "uncommon": [
        "common",
        "rare",
        "rusty",
        "dusty",
        "cobwebbed",
        "ruined",
        "broken",
        "untouched",
        "etched",
        "carved",
        "worn",
        "pristine",
        "polished",
        "chipped",
        "flawless",
        "mended",
        "damaged",
        "old",
        "durable",
        "weakened",
        "fragile",
        "shiny",
        "fine",
        "adequate",
        "dirty",
        "barbed",
        "thorny",
    ]
}


MATERIALS = [
    "golden",
    "silver",
    "glass",
    "bone",
    "onyx",
    "obsidian",
    "amethyst",
    "iron",
    "steel",
    "leather",
    "wood",
    "emerald",
    "jade",
    "turquoise",
    "ivory",
    "bronze",
    "copper",
    "meteorite",
    "stone",
    "adamantine",
]